kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azad-kube-proxy
rules:
- apiGroups:
  - ""
  resources:
  - "users"
  - "groups"
  - "serviceaccounts"
  verbs:
  - "impersonate"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "userextras/scopes"
  verbs:
  - "impersonate"