apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "azad-kube-proxy.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "azad-kube-proxy.selectorLabels" . | nindent 6 }}
