{{- if .Values.pdb.enabled }}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "azad-kube-proxy.fullname" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "azad-kube-proxy.selectorLabels" . | nindent 6 }}
{{- end }}
