apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azad-kube-proxy.serviceAccountName" . }}
  labels:
    {{- include "azad-kube-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
