apiVersion: v1
kind: Namespace
metadata:
  name: azad-kube-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azad-kube-proxy
  namespace: azad-kube-proxy
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azad-kube-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azad-kube-proxy
subjects:
- kind: ServiceAccount
  name: azad-kube-proxy
  namespace: azad-kube-proxy
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azad-kube-proxy
rules:
- apiGroups:
  - ""
  resources:
  - "users"
  - "groups"
  - "serviceaccounts"
  verbs:
  - "impersonate"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "userextras/scopes"
  - "tokenreviews"
  verbs:
  - "create"
  - "impersonate"
