name: Coverage main

on:
  push:
    branches:
      - main

jobs:
  coverage-main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.2"
      - name: coverage
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          TEST_USER_SP_CLIENT_ID: ${{ secrets.TEST_USER_SP_CLIENT_ID }}
          TEST_USER_SP_CLIENT_SECRET: ${{ secrets.TEST_USER_SP_CLIENT_SECRET }}
          TEST_USER_SP_RESOURCE: ${{ secrets.TEST_USER_SP_RESOURCE }}
          TEST_USER_SP_OBJECT_ID: ${{ secrets.TEST_USER_SP_OBJECT_ID }}
          TEST_USER_OBJECT_ID: ${{ secrets.TEST_USER_OBJECT_ID }}
        run: |
          mkdir -p tmp
          make cover
      - name: Send coverage to coverall
        uses: shogo82148/actions-goveralls@v1.4.7
        with:
          path-to-profile: tmp/coverage.out
          ignore: cmd/azad-kube-proxy/main.go,pkg/proxy/proxy.go,cmd/kubectl-azad-proxy/main.go
