name: release-helm-chart

on:
  release:
    types:
      - published

jobs:
  release-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: "v4.4.1"
      - name: Get GitHub Tag
        id: get_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Update Helm chart version and verify no changes
        env:
          GITHUB_TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          yq e '.version=env(GITHUB_TAG)' -i charts/azad-kube-proxy/Chart.yaml
          yq e '.appVersion=env(GITHUB_TAG)' -i charts/azad-kube-proxy/Chart.yaml
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
