name: Release Plugin

on:
  release:
    types:
      - published

jobs:
  release-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo VERSION=${VERSION} >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.1.1
        env:
          VERSION: ${{ steps.prep.outputs.VERSION }}
          REVISION: ${{ github.sha }}
          CREATED: ${{ steps.prep.outputs.BUILD_DATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.43
